# Generated by Django 5.1 on 2024-08-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_task_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, '낮음'), (2, '중간'), (3, '높음')], default=2),
        ),
    ]
